"""Add agent_type to agent_sessions

Revision ID: 0eed7ae4d53b
Revises: a39bdb664000
Create Date: 2025-10-31 10:34:12.311415

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0eed7ae4d53b"
down_revision: Union[str, None] = "a39bdb664000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_sessions", sa.Column("agent_type", sa.String(length=50), nullable=False))
    op.create_index(op.f("ix_agent_sessions_agent_type"), "agent_sessions", ["agent_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_sessions_agent_type"), table_name="agent_sessions")
    op.drop_column("agent_sessions", "agent_type")
    # ### end Alembic commands ###
