"""Add agent_name column to agent_sessions

Revision ID: 5d27842857f7
Revises: 0eed7ae4d53b
Create Date: 2025-01-19 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d27842857f7"
down_revision: Union[str, None] = "0eed7ae4d53b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_sessions", sa.Column("agent_name", sa.String(length=50), nullable=False))
    op.create_index(op.f("ix_agent_sessions_agent_name"), "agent_sessions", ["agent_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_sessions_agent_name"), table_name="agent_sessions")
    op.drop_column("agent_sessions", "agent_name")
    # ### end Alembic commands ###
